name: Release Build

on:
  push:
    tags: ["*"]

env:
  EXECUTABLE_NAME: "qubic-cli"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_type: Release
            cpp_compiler: cl
            artifact_suffix: "Windows-MSVC.exe"
          - os: ubuntu-latest
            build_type: Release
            cpp_compiler: g++
            artifact_suffix: "Linux-GCC"
          - os: ubuntu-latest
            build_type: Release
            cpp_compiler: clang++
            artifact_suffix: "Linux-Clang"

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S .

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Rename and Move Binary
        shell: bash
        run: |
          NEW_NAME="${{ env.EXECUTABLE_NAME }}-${{ matrix.artifact_suffix }}"
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv ./build/Release/*.exe ./$NEW_NAME
          else
            mv ./build/${{ env.EXECUTABLE_NAME }} ./$NEW_NAME
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.EXECUTABLE_NAME }}-${{ matrix.artifact_suffix }}
          body: |
            ## Automated Build
            **Precaution:** These binaries are compiled by github workflow. It's recommended that you should download the source code and compile it yourself.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}